### ISSUE TITLE
Unable to delete software package having trailing blank in the Version string

### ISSUE THREAD

**Issue by haubi** [bdeployteam/bdeploy#4]
Somehow I have managed to upload a software package into the Central server, having a Version string with trailing blank (0x20, by copy&paste), even if I remember I got some error box about trailing blanks somewhere during the upload.

While having problems using that package is fine, being unable to Delete that package is ... confusing at best.

That trailing blank becomes visible in the file name when downloading that package, as in '...202207211014 .zip'.

**Comment by mduft** [comment]
Hey :) Is there a reason why you work on the BDeploy GitHub repo? We're using the SSI internal repository and tracker typically...

**Comment by haubi** [comment]
Ah - and I've wondered already why I'm the reporter of the first issue here. Nevertheless, I would prefer public communication channels for public projects anyway, but that's a different topic.

**Comment by mduft** [comment]
As discussed please use the internal bug tracker for now.
